### ISSUE TITLE
the size doesn't fit iphone5 nor iphone6p

### ISSUE THREAD

**Issue by zy-candone** [MitchellMalleo/MMScrollPresenter#5]
this scrollview works fine with iphone6 but seems layout won't fit in iphone5 nor iphone6p. in iphone, the display is smaller than it shall be and iphone6p, where there is blank area in right side of screen. 
I simply checked the code, didn't find place to correct easily. :-(

**Comment by MitchellMalleo** [comment]
Hey zy-candone,

I have a solution for auto layout and non-auto layout views. If you're using a non-auto layout nib, adding this line [self.mmScrollPresenter setFrame:CGRectMake(0, 0, [[UIScreen mainScreen] bounds].size.width, self.mmScrollPresenter.frame.size.height)]; should fix all your resizing issues. Furthermore, if you're using auto layout, you'll have to add two constraints to your MMScrollPresenter. The two constraints you'll be adding are ones that set the horizontal spacing to zero for the left and right sides. I've updated the sample project to reflect these changes. There are other solutions to this problem, but these seemed the most applicable for what you're describing. Hope this helps. (:
