### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by zy-candone** [MitchellMalleo/MMScrollPresenter#6]
the memory usage is massive. when i loaded it up, the memory usage jumped to 180M+ and it obviously slows down the user experience, you will feel kind of stuck for a second for 2. As improvement proposal, this memory usage shall be optimized. I can look into it when i have a bit more time. Just let you know the feedback right now :-)

**Comment by MitchellMalleo** [comment]
Hey zy-candone,

It looks like much of the memory is being allocated due to the large images that I'm using in the example. That being said, any improvements are much appreciated, and I'll be happy to add you to the contributors list.
