### ISSUE TITLE
title not appear perfectly .

### ISSUE THREAD

**Issue by bharathi91** [MitchellMalleo/MMScrollPresenter#7]
Control works like charm when i supply 3 objects,.
WHEN i supply 2 objects or more than 3 objects instead, the title view frame is not properly set , and extends to the next page too.

**Comment by MitchellMalleo** [comment]
Hey bharathi91,

Thanks for pointing out this issue. After some digging it looks like I had a small math issue in one of my functions for drawing the frames. I tested out the new code with 2, 3, 4, and 5 pages respectively so the issue should be resolved. Either pull down a new version of the repository or `pod update` your cocoapods and you should be good to go. (:

**Comment by bharathi91** [comment]
Thanks for the quick response.I ll Check with the new lib.
